2023-03-13 12:02:41,938 - INFO - Iniciamos el proceso
2023-03-13 12:02:41,942 - ERROR - Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Traceback (most recent call last):
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/log_example.py", line 10, in <module>
    df_camiones = pd.read_excel(
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1695, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 556, in __init__
    import_optional_dependency("openpyxl")
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/compat/_optional.py", line 144, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2023-03-13 12:02:57,160 - INFO - Iniciamos el proceso
2023-03-13 12:02:57,552 - INFO - Leido el fichero BASE DE DATOS 2022 PRUEBA.xlsx
2023-03-13 12:15:22,843 - ERROR - Iniciamos el proceso
2023-03-13 12:15:23,758 - INFO - Leido el fichero BASE DE DATOS 2022 PRUEBA.xlsx
2023-03-13 12:15:33,910 - INFO - Leido el fichero BASE DE DATOS 2022 PRUEBA.xlsx
2023-03-13 12:15:52,420 - INFO - Iniciamos el proceso
2023-03-13 12:15:53,671 - INFO - Leido el fichero BASE DE DATOS 2022 PRUEBA.xlsx
2023-03-13 12:16:10,057 - INFO - Iniciamos el proceso
2023-03-13 12:16:10,057 - ERROR - [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
Traceback (most recent call last):
  File "/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/log_example.py", line 10, in <module>
    df_camiones = pd.read_excel(
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1652, in __init__
    ext = inspect_excel_format(
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1525, in inspect_excel_format
    with get_handle(
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
